# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8c541391f95fe3f87a099b63f28e63deeb00d4e94065897f0ef6f88042ad8e6c433e7a75b4f20a9ba28657c99954276afb4409ec0af90590c2f7e848d7fbce6

test:
  secret_key_base: 213f16610b594696c2b516dddd68606deaf93d54c6e404429b6a0b402891723d01b1c9f8a07cdd1fe717f7e01ffd6c9bee6497c9a32450dd0bdf824b1508152c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
